DetoxActionHandlers: replace string status with JSON description.
wix/Detox pull request #3064
Opened 2021-11-11 12:30 UTC by asafkorem

Replace the old string sync-status with a JSON description (in Android), as part of the sync-logs unification (iOS and Android).

See how it will be formatted [here](https://github.com/wix/Detox/pull/3063).

2021-11-11 13:00 UTC, asafkorem commented
retest this please

2021-12-05 14:03 UTC, asafkorem commented
@jonathanmos @d4vidi pushed native tests, integration tests are still missing. 
However, this should not block the reviews.

2021-12-07 16:28 UTC, d4vidi requested changes
1. Align documentation: debug sync guide (https://wix.github.io/Detox/docs/troubleshooting/synchronization/)
1. Inline comments

2021-12-07 16:28 UTC, d4vidi commented on detox/android/detox/src/testFull/java/com/wix/detox/reactnative/idlingresources/AsyncStorageIdlingResourceSpec.kt
> +                assertThat(uut.getJSONDescription()).isEqualTo(mapOf("name" to "io"))
+1 point, Level Up

2021-12-07 16:28 UTC, d4vidi commented on detox/android/detox/src/testFull/java/com/wix/detox/adapters/server/DetoxActionHandlersSpec.kt
> +            it("should return busy app status") {
split 3-ways

2021-12-07 16:28 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt
> +                "Bridge.executeJSCall"
not needed

2021-12-07 16:28 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt
> +                "onBatchComplete"
not needed

2021-12-07 16:28 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt
> +                        }
```suggestion
                          immutableMapOf<String, Any>("thread" to thread)
                            .let {
                              if (executionType != null) {
                                it["execution_type"] = executionType
                              } 
                            }
```

2021-12-07 16:28 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt
>      : DetoxActionHandler {
Extract class?

2021-12-08 09:09 UTC, asafkorem commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/BridgeIdlingResource.java
> +        jsonDescription.put(IdlingResourceConstants.RESOURCE_NAME_KEY, "one_time_event");
done :+1:

2021-12-08 10:23 UTC, asafkorem commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/BridgeIdlingResource.java
> +        return jsonDescription;
done

2021-12-08 10:27 UTC, asafkorem commented on detox/android/detox/src/testFull/java/com/wix/detox/adapters/server/DetoxActionHandlersSpec.kt
> +            it("should return busy app status") {
done

2021-12-08 10:34 UTC, asafkorem commented on detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt
> +                "Bridge.executeJSCall"
💯  good catch

2021-12-08 10:37 UTC, asafkorem commented on detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt
> +                        }
`.apply {` seems to fit better here

2021-12-08 10:43 UTC, asafkorem commented on detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt
>      : DetoxActionHandler {
done

2021-12-08 12:15 UTC, asafkorem commented
Fixed and squashed.

2021-12-08 13:35 UTC, merged