Migrate to rn67
wix/Detox pull request #3202
Opened 2022-02-01 09:43 UTC by jonathanmos

## Description
Update Detox to use RN67. This fixes issue #3197 

> _For features/enhancements:_
 - [X] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

2022-02-01 09:48 UTC, asafkorem approved these changes
LGTM

2022-02-02 08:26 UTC, asafkorem requested changes

2022-02-02 08:26 UTC, asafkorem commented on detox/test/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-bin.zip
Is this safe for RN v67? was there a special reason why they bumped this version?

2022-02-13 11:34 UTC, d4vidi commented on README.md
> +| ≤0.67.x | ≥0.64, ≤0.67 - Visibility edge-case: see this [RN issue](https://github.com/facebook/react-native/issues/23870) \* |
🔥

2022-02-13 11:35 UTC, d4vidi commented on detox/test/android/build.gradle
> +        maven { url 'https://www.jitpack.io' }
Is this really needed?

2022-02-13 11:37 UTC, d4vidi commented on scripts/ci.no.generate.sh
> +run_f "lerna run test --ignore=generation"
great

2022-02-22 14:20 UTC, d4vidi approved these changes
- Please double check the jitpack.io thing
- Please also attach links to green CI builds before merging (android & ios test jobs and android & ios example projects jobs) 🙏🏻

2022-02-23 10:26 UTC, jonathanmos commented
Green builds for ios/android 64/66 test jobs -> https://jenkins-oss.wixpress.com/job/multi-detox-pr/4219/
Green builds for ios 67 test job -> https://jenkins-oss.wixpress.com/view/all/job/detox-ios-67-branch/11/
Green build for android 67 test job -> https://jenkins-oss.wixpress.com/view/all/job/detox-android-67-x-branch/8/

2022-02-24 10:10 UTC, d4vidi requested changes
Almost there... As the last mile, please be sure to run the demo-projects job using RN .67 as well. Also, *please create an iOS demo-project job* and wire it to our PR so it is executed regularly.

2022-03-01 12:06 UTC, d4vidi commented
@jonathanmos Touch-base; I see the current gaps are:
- Reinstating the CI-script for the iOS example app (as in my previous comment)
- Making the necessary adjustments in the buildkite scripts, in order to effectively upgrade the CI jobs to RN .67

2022-03-02 13:46 UTC, asafkorem commented
I removed detox-instruments phase from the iOS script, although I tried to make it work (I followed the instruments doc, didn't helped). I can investigate its issues separately, regardless of this PR.

2022-03-03 13:07 UTC, asafkorem commented
> @jonathanmos Touch-base; I see the current gaps are:
> 
> Reinstating the CI-script for the iOS example app (as in my previous comment)
> Making the necessary adjustments in the buildkite scripts, in order to effectively upgrade the CI jobs to RN .67

Done. Is there anything left that blocks us from merging this PR? @d4vidi @jonathanmos 

Jenkins fails on the Android jobs with unrelated EACCES error (in other PRs also), however Buildkite pass so I don't care much..

2022-03-14 09:19 UTC, merged

2022-03-15 13:08 UTC, d4vidi commented
!!!!!!