Enable Genymotion debug
wix/Detox pull request #3231
Opened 2022-02-22 15:53 UTC by jonathanmos

## Description
Enable running debug tests on Genycloud (discussed in [this](https://github.com/wix/Detox/issues/2655) issue)

2022-02-23 08:48 UTC, noomorph commented on detox/test/e2e/setup.js
> +  await device.reverseTcpPort(8081);
Is that port of the Metro bundler?

2022-03-01 13:28 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/Detox.java
> +    private static final String DEBUG_HOST_KEY = "debug_http_host";
```suggestion
    private static final String RN_DEBUG_HOST_KEY = "debug_http_host";
```

2022-03-01 13:35 UTC, d4vidi requested changes
I'm not mentally ready to do this world-wide, as implicated by this PR.
I think we should first introduce a more local solution:
1. Specify the preferences tweak in our internal project's `DetoxTest.java`
2. Call `device.reverseTcpPort(8081)` in the single test suite where it really matters, in the associated project.

2022-03-22 15:38 UTC, d4vidi commented
@jonathanmos I think we should reiterate this, and decide on one of these 2 options:
1. Avoid integrating into Detox at this point, and solve this locally (as I've previously suggested).
2. Introduce this into Detox in a more generic and holistic way. For example, instead of `isGenymotion`, we should allow for accepting an argument that holds the URL to override with (e.g. `localhost:8081`). Also, if we do this, then we'd also have to introduce a test scheme that would run in Debug and verify that this thing works continuously.

2022-03-28 12:04 UTC, closed without merging

2022-03-28 12:05 UTC, jonathanmos commented
Will be solved locally