Add appcompat dependency to docs
wix/Detox pull request #3412
Opened 2022-05-22 08:11 UTC by jonathanmos

## Description
When a project is setup through react-native init, the following appcompat dependency is not added. 

    implementation 'androidx.appcompat:appcompat:1.1.0'

This later causes the following error when building Detox in release mode:

    Execution failed for task ':app:processReleaseAndroidTestResources'.
    > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
       > Android resource linking failed
         ERROR:: AAPT: error: resource style/Widget.AppCompat.TextView ...

In this pull request I have updated the docs with the solution for this issue.

2022-05-22 08:36 UTC, noomorph approved these changes

2022-05-22 11:30 UTC, d4vidi requested changes
This is great but needs polishing.

2022-05-22 11:30 UTC, d4vidi commented on docs/Troubleshooting.BuildingTheApp.md
> +### Problem: AAPT
Lovin' this troubleshooting section. The heading, on the other hand, isn't very descriptive. `AAPT` can mean so many things...

2022-05-22 11:30 UTC, d4vidi commented on docs/Introduction.Android.md
> +    implementation 'androidx.appcompat:appcompat:1.1.0'
This is definitely the right page for this but I don't like it under this section (named, "Add the native detox dependency"). 'Need to put things under the right context...

2022-05-22 11:31 UTC, d4vidi commented
@igorgn on a different matter: any ideas why buildkite appears twice (regular and pr)?

![image](https://user-images.githubusercontent.com/9818880/169693033-f49c839a-9ec8-4463-b216-0bb9f8bb2bcd.png)

2022-05-22 13:08 UTC, igorgn commented
@d4vidi It is because branch build was triggered manually and not via '_git push_'. "_buildkite/detox/pr_" is there because this check is set as "_Required_", thus it will be present in **every** PR.  But manual build is considered as a regular "**buildkite/detox**", making it a separate check and thus we have 2 checks. 

In buildkite we can disable this behaviour, leaving only "**buildkite/detox**" check, i.e. PR checks also would be marked as "**buildkite/detox**"

2022-05-22 15:48 UTC, d4vidi commented on docs/Troubleshooting.BuildingTheApp.md
> +    implementation 'androidx.appcompat:appcompat:1.1.0'
@jonathanmos Sorry I haven't mentioned this before (although it _did_ come to mind): Using the static `1.1.0` version is tricky here. I think we should add some kind of an indication saying that `1.1.0` may not be the latest/most suitable version for the user's project, etc.

2022-06-01 10:43 UTC, d4vidi commented on docs/Introduction.Android.md
> +    implementation 'androidx.appcompat:appcompat:1.1.0'
@jonathanmos version notice here too

2022-06-01 12:46 UTC, d4vidi approved these changes

2022-06-01 12:56 UTC, merged