Support getAttributes on multiple views on Android
wix/Detox pull request #3464
Opened 2022-07-03 14:39 UTC by jonathanmos

## Description
Add Android support for running getAttributes on more than one matching view

- This pull request addresses the issue described here: #3196

2022-07-06 15:15 UTC, asafkorem requested changes

2022-07-06 15:15 UTC, asafkorem commented on detox/src/android/AndroidExpect.test.js
> +          mockExecutor.executeResult = ['{"result": [{"text": "hello", "value": 1}]}'];
revisit

2022-07-06 15:15 UTC, asafkorem commented on detox/src/android/core/NativeElement.js
>      // if (!(matcher instanceof NativeMatcher)) throw new DetoxRuntimeError(`Element _selectElementWithMatcher argument must be a valid NativeMatcher, got ${typeof matcher}`);
we can remove this comment IMO

2022-07-06 15:15 UTC, asafkorem commented on detox/src/android/core/NativeElement.js
> +    return await new ActionInteraction(this._invocationManager, this, new actions.GetAttributes()).execute();
:+1:

2022-07-10 08:44 UTC, asafkorem approved these changes
LGTM, great work

2022-07-10 08:45 UTC, asafkorem commented
I suggest to squash the commits to have meaningful names and context for the changes.

2022-07-21 12:53 UTC, d4vidi requested changes

2022-07-21 12:53 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/espresso/MultiViewActionWithResult.kt
> +        return if (results.size == 1) results.first() else elementsObject
Better to not perform the JSON formatting etc. when it is not necessary (i.e. in the single-result case)

2022-07-21 12:53 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/espresso/MultiViewActionWithResult.kt
> +    fun performOnView(viewMatcher: Matcher<View>): Any {
The name is misleading because the action is performed over _multiple_ views (potentially), based on a matcher.

2022-07-21 12:53 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/espresso/MultiViewActionWithResult.kt
> +abstract class MultiViewActionWithResult<R> : ViewActionWithResult<R> {
So overall, this design is okay - but it's not good enough. There's some smell coming from the fact that the `getResult()` method is misused; Loosely speaking, one could say it violates the [Liskov Substitution Principle](https://blog.knoldus.com/what-is-liskov-substitution-principle-lsp-with-real-world-examples/#:~:text=Simply%20put%2C%20the%20Liskov%20Substitution,the%20objects%20of%20our%20superclass.).

Let's discuss where _conceptually_ that smell could be coming from.

2022-07-24 07:31 UTC, jonathanmos commented on detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxViewInteraction.kt
> +    }
DetoxViewInteraction wraps Espresso ViewInteraction, and ViewInteraction exposes these public methods

2022-07-24 12:35 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxViewInteraction.kt
> +    }
Well we have no control over Espresso, but we do have control over Detox 🤔

2022-09-01 11:11 UTC, mizinin commented
Is there any chance it will get into master?

2023-01-05 06:13 UTC, pradeipp commented
not stale

2023-03-09 08:49 UTC, Dr0pG commented
This PR will get into master soon?

2023-03-28 20:43 UTC, d4vidi commented
> This PR will get into master soon?

I can't promise anything but I can say we've reprioritized things and that it's in our upcoming plans to revisit this.

2023-07-05 22:45 UTC, eyalzajfman commented
Is there any update on this?

2023-09-06 05:58 UTC, closed without merging

2023-09-06 11:03 UTC, asafkorem commented
This functionality will be introduced to `getAttributes` after this pull request: https://github.com/wix/Detox/pull/4180.
I'm closing this PR for now.