feat: add invocation trace events.
wix/Detox pull request #3559
Opened 2022-08-16 14:41 UTC by asafkorem

Add invocation (actions and expectations) started & ended events, along with their stack trace.

As addressed in #3536.

2022-08-16 15:15 UTC, asafkorem commented
@jonathanmos I made some changes, most of them as agreed f2f, please review 🙏🏼 🙂

2022-08-17 05:54 UTC, jonathanmos requested changes

2022-08-17 05:54 UTC, jonathanmos commented on detox/src/android/core/NativeElement.js
> +    const traceDescription = actionDescription.multiTap();
multiTap is missing times arg

2022-08-17 05:54 UTC, jonathanmos commented on detox/src/android/interactions/native.js
> +  constructor(invocationManager, element, action, description) {
we need to change to traceDescription to match the rest

2022-08-17 05:54 UTC, jonathanmos commented on detox/src/ios/expectTwo.js
>      const invocation = this.createInvocation(action, null, ...params);
need to change these to traceDescription to match the rest

2022-08-17 05:54 UTC, jonathanmos commented on detox/src/ios/expectTwo.js
>      const invocation = this.createInvocation(action, targetElement, ...params);
same as previous: description -> traceDescription

2022-08-17 11:38 UTC, asafkorem commented on detox/src/android/espressoapi/EspressoDetox.js
> +    if (typeof urls !== 'object' || !urls instanceof Array) {
Why?

2022-08-18 12:25 UTC, d4vidi commented on detox/src/android/espressoapi/EspressoDetox.js
> +    if (typeof urls !== 'object' || !urls instanceof Array) {
what about `_.isArray`, `_.isObject`?

2022-08-20 18:15 UTC, asafkorem commented on detox/src/android/espressoapi/EspressoDetox.js
> +    if (typeof urls !== 'object' || !urls instanceof Array) {
That's autogenerated code actually 😅

2022-08-22 20:29 UTC, asafkorem commented
Squashed commits with meaningful commit messages.

2022-08-25 11:42 UTC, jonathanmos approved these changes

2022-08-25 11:43 UTC, merged

2022-08-25 11:44 UTC, jonathanmos approved these changes