bugfix: avd validator emulator version should obey `headless`
wix/Detox pull request #3614
Opened 2022-09-27 15:23 UTC by paulrostorp

## Description
This is a bug
- This pull request addresses the issue described here: #3613 

In this pull request, I have forwarded the `headless` config option to the `AVDValidator` so that the existing emulator version query can operate as expected and in accordance to the configuration provided by the user

2022-09-27 15:28 UTC, noomorph commented
Unit tests? nothing to change?

2022-09-28 09:04 UTC, paulrostorp commented
@noomorph Hi, I've added two test cases and fixed the broken one 😄

2022-10-02 08:39 UTC, noomorph commented
@d4vidi @asafkorem please review the unit tests for quality (I'm a bit worried about non-explicitness of expected booleans there, e.g.: `expect(avdValidator.validate).toHaveBeenCalledWith(avdName, deviceConfig.headless);`) where it is not clear what `deviceConfig.headless` is.

2022-10-02 08:51 UTC, asafkorem commented
@noomorph np, I'll review that.

2022-10-02 09:30 UTC, asafkorem requested changes
overall looks good to me, minor suggestion, and we can merge it.

2022-10-02 09:30 UTC, asafkorem commented on detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.test.js
> +      expect(avdValidator.validate).toHaveBeenCalledWith(avdName, deviceConfig.headless);
Yarik has a good point. Isn't `deviceConfig.headless` is `undefined` here?

2022-10-02 09:30 UTC, asafkorem commented on detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.test.js
> +      expect(avdValidator.validate).toHaveBeenCalledWith(avdName, deviceConfig.headless);
It should pass without `deviceConfig.headless` arg under the expectation, and I think it's better to be explicit on that:
```suggestion
      expect(avdValidator.validate).toHaveBeenCalledWith(avdName);
```

2022-10-02 14:59 UTC, asafkorem commented on detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.test.js
> +      expect(avdValidator.validate).toHaveBeenCalledWith(avdName, deviceConfig.headless);
I'm taking the liberty of committing this suggestion 😅

2022-10-02 20:48 UTC, asafkorem approved these changes

2022-10-02 20:55 UTC, merged

2022-10-03 09:00 UTC, asafkorem commented
Thanks @paulrostorp, [Detox v19.12.4](https://github.com/wix/Detox/releases/tag/19.12.4) was released with your fix 👑