Fix(Android): Emulator boot not detected >= api 31
wix/Detox pull request #3672
Opened 2022-11-07 08:10 UTC by jonathanmos

## Description
Detect when emulator boots >= api 31

2022-11-07 09:39 UTC, noomorph requested changes
@jonathanmos think about a different approach: https://github.com/wix/Detox/compare/next...draft/android-emulator?expand=1

2022-11-13 21:41 UTC, d4vidi reviewed
Generally approved with these 2 caveats:
- In the very least, this has to be tested manually against numerous SDK's, cold/quick boots etc. using new / old adb binaries and make sure wait-for-boot always applies.
- Need to set up an automated testing environment for this, in order to test SDK ≥31 regularly (at least the launch phase).

2022-11-13 21:41 UTC, d4vidi commented on detox/src/devices/allocation/drivers/android/emulator/launchEmulatorProcess.js
> -const { Tail } = require('tail');
Does this mean we can get rid of `tail` as a module altogether?

2022-11-13 21:41 UTC, d4vidi commented on detox/src/devices/common/drivers/android/exec/ADB.js
> +    return await this.adbCmd(deviceId, 'wait-for-device');
Test coverage

2022-11-13 21:41 UTC, d4vidi commented on detox/src/devices/allocation/drivers/android/emulator/launchEmulatorProcess.js
> +  adb.waitForDevice(adbName).then(() => childProcessPromise._cpResolve());
What happens if something indeed goes wrong here? Emulator crash or whatever? Will it throw or hang forever?

2022-11-15 13:14 UTC, jonathanmos commented on detox/src/devices/common/drivers/android/exec/ADB.js
> +    return await this.adbCmd(deviceId, 'wait-for-device');
Added unit test for this method

2022-11-15 13:22 UTC, d4vidi approved these changes

2022-11-16 09:59 UTC, noomorph approved these changes

2022-11-16 10:05 UTC, merged