feat(android): Detect busy background threads
wix/Detox pull request #3718
Opened 2022-11-20 13:05 UTC by jonathanmos

## Description
Espresso considers the device not idle if it has active asynctasks, however until now debug-sync wasn't able to see these tasks and as a result would print messages of "Device seems to be idle", instead of actually indicating the issue. In this PR, the ability to check the status of asynctasks has been added in order to provide accurate sync debugging. 

- This pull request addresses the issue described here: #3617

2022-11-23 20:16 UTC, d4vidi requested changes
So besides the inline notes, my impression is that the roles of `DetoxBusyResourceHelper` and to some extent `DetoxBusyResource` itself have been too loosely defined. As I understand it, there are largely 2 layers involved in this mechanism - adhering to the hexagonal / port&adapter architecture:
1. The requests inbound/outbound layer, which in other words is the network "port".
2. The core, which interrogates the system's status and returns some abstract representation of the result (i.e. a list of "busy resources").

`QueryStatusActionHandler` resides in the 1st layer. The 2nd layer is `TestEngineFacade` and below. `DetoxBusyResourceHelper` seems to violate that separation by being tightly associated with `DetoxBusyResource`, on the one hand, but performing the formatting work which should stay under the jurisdiction of `QueryStatusActionHandler`.

You must reconsider this design, and provide an alternative which better aligns with the architecture.

2022-11-23 20:16 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/asynctask/DetoxBusyResource.kt
> +    }
Feels weird to have this just for testing. Would it make more sense to use `constructor(IdlingResource)` with a mocked idling resource?

2022-11-28 10:01 UTC, jonathanmos commented on detox/src/client/actions/formatters/__snapshots__/SyncStatusFormatter.test.js.snap
> +`;
What if in the future we detect background work that is not caused by an asynctask? The way that this is currently written it's extensible, whereas to print a single statement locks it to asynctasks as the cause

2022-11-28 10:02 UTC, jonathanmos commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/asynctask/DetoxBusyResource.kt
> +    }
This was added for unit test comparisons

2022-12-08 12:34 UTC, d4vidi approved these changes

2022-12-08 12:37 UTC, merged

2022-12-13 10:01 UTC, asafkorem commented
Thanks @jonathanmos, Detox version [20.1.0](https://github.com/wix/Detox/releases/tag/20.1.0) has been released with this change.