Chore/lint errors
wix/Detox pull request #3719
Opened 2022-11-20 17:15 UTC by noomorph

## Description

- This pull request addresses the issue described here: #3292

Mostly, I fix here unused vars.

2022-12-23 09:40 UTC, noomorph commented
Also I extracted one more pull request out of this one: #3778. 

Please make sure to review it too.

2022-12-25 16:52 UTC, d4vidi commented on detox/src/artifacts/templates/plugin/ArtifactPlugin.js
> +  async onBeforeLaunchApp(_event) {
I'm not very enthusiastic about this approach. It makes the argument's crippled name the official one, for the API. It makes it weird esp. in these cases where classes inherit these methods -- both in calling `super()`, and when called as an external API.

2022-12-25 16:53 UTC, d4vidi requested changes
See my single note on this. I don't like this solution...

2022-12-27 13:51 UTC, noomorph commented on detox/.eslintrc.js
> +    'no-unused-vars': 'off',
We rely on `@typescript-eslint/no-unused-vars` for that instead.

2022-12-27 13:55 UTC, noomorph commented
Changed the solution to a less intrusive one.

2022-12-27 13:56 UTC, merged