docs: update android setup with react native 0.71
wix/Detox pull request #3869
Opened 2023-01-24 16:03 UTC by xiongemi

## Description

- This pull request addresses the issue described here: #<?>

In this pull request, I have updates the docs for android setup with react native 71

---

> _For features/enhancements:_
 - [x] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [x] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

2023-01-25 09:16 UTC, noomorph requested changes

2023-01-25 09:16 UTC, noomorph commented on docs/introduction/project-setup.mdx
> +      ndkVersion = "23.1.7779620"
Isn't the version too specific? I guess just after 2-4 weeks the build number `7779620` will be different when someone installs the latest 23.x NDK. @d4vidi , @xiongemi please advise.

2023-01-25 09:16 UTC, noomorph commented on docs/introduction/project-setup.mdx
> +}
```suggestion
}

```

Maybe better to separate with an extra newline.

2023-01-25 09:16 UTC, noomorph commented on docs/introduction/project-setup.mdx
> +    repositories {
Could you please keep indent level at 2?

2023-01-25 09:16 UTC, noomorph commented on docs/introduction/project-setup.mdx
> ++           // https://wix.github.io/Detox/docs/introduction/project-setup
```suggestion
```

I guess this comment is redundant here.

2023-01-29 21:58 UTC, d4vidi commented
We have known issues with SDK v33 (so can't recommend it in the docs) and are not officially compliant with RN v0.71 yet.
I have to close this in favor of #3884, which we will get to sometime in Q2.

2023-01-29 21:59 UTC, closed without merging