WIP: XCUITest integration.
wix/Detox pull request #3975
Opened 2023-03-08 13:52 UTC by asafkorem

# THIS IS A **WORK IN PROGRESS** BRANCH

![image](https://user-images.githubusercontent.com/55082339/223729371-05518a40-ac39-4151-90ad-7fbad1c78b7d.png)

This is a draft pull request for the first phase of XCUITest integration into Detox-iOS ("**Reimplement Detox iOS**").
**See epic issue:** https://github.com/wix/Detox/issues/3208

2023-03-08 15:16 UTC, d4vidi commented
![image](https://user-images.githubusercontent.com/9818880/223752286-d0356ad3-563c-4250-bb33-cad97bce39f5.png)

I see a new dawn

2023-12-27 18:21 UTC, noomorph requested changes

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/XCUITestUtils.js
> +  const result = exec(command, options);
Is there a reason why you didn't use spawn from our Detox `utils/childProcess`?

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/XCUITestUtils.js
> +  return exec(`osascript -e '${appleScript}'`, options);
Why didn't you use `osascript.execute` here?

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/XCUITestUtils.js
> +    function(err, _, __) {
Why do you need `_` and `__` params?

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/XCUITestUtils.js
> +  let didCallback = false;
Was there any good reason not to use promises here?

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/XCUITestUtils.js
> +      await exec(`nc -z localhost ${testTargetServerPort}`);
This looks too heavy. You could probe a port using `net`.Socket package, I guess.

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/XCUITestUtils.js
> +  while (!isServerUp && retries++ < 90) {
We have already utils/retry in Detox, so you don't need to write this twice.

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/XCUITestUtils.js
> +    log.debug(`[XCUITest] Killing the process that allows network permissions (timed-out)`);
Well , usually you can pass a timeout and killSignal to a process to make code simpler:

![image](https://github.com/wix/Detox/assets/1962469/716b3f3a-0f86-406e-a991-e9402a31483c)

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/XCUITestUtils.js
> +        log.error(`[XCUITest] Failed to approve network permissions for XCUITest target:\n\t${err}`);
Is this actually fatal? If yes, do we do enough to stop a hopeless endeavor early?

2023-12-27 18:21 UTC, noomorph commented on detox/src/devices/runtime/drivers/ios/allowNetworkPermissionsXCUITest.scpt
> +        repeat until (exists button "Allow" of window 1)
I just wonder if I have anything other hanging in UserNotificationCenter, wouldn't it block this loop (because it looks at `window 1`)?

2023-12-27 18:21 UTC, noomorph commented on detox/src/server/DetoxSession.js
> +    console.log(`app joined session ${this.id}`);
This definitely looks redundant.

2023-12-27 18:21 UTC, noomorph commented on detox/src/server/DetoxSession.js
> +      console.warn(`app joined session ${this.id} without a tester`);
If this is a noteworthy event, use log.warn

2023-12-27 18:21 UTC, noomorph commented on detox/src/server/DetoxSession.js
> +    console.log(`notify: pendingAppStatus=${this._pendingAppStatus}, pendingTesterStatus=${this._pendingTesterStatus}\n\n`);
Another console.l

2023-12-27 18:21 UTC, noomorph commented on detox/src/server/DetoxSessionManager.js
> +    console.log('registerSession', role, sessionId);
Use logger or don't log, please.

2023-12-27 18:21 UTC, noomorph commented on detox/src/server/handlers/AnonymousConnectionHandler.js
> +    console.log(`[DetoxServer.js/LOGIN] role=${action.params.role}, sessionId=${action.params.sessionId}`);
console.log

2023-12-27 18:21 UTC, noomorph commented on detox/src/utils/childProcess/exec.js
> +    maxBuffer = 1024 * 1024,
Could you please remind where this was needed?

2024-03-31 14:09 UTC, asafkorem commented
This PR is outdated. I'm about to push the integration in smaller changes.

2024-03-31 14:09 UTC, closed without merging