Bugfix/2787 scrollto gets stuck on android
wix/Detox pull request #4327
Opened 2024-01-04 15:46 UTC by gosha212

## Description

- This pull request addresses the issue described here: #2787 #4312

In this pull request, I have fixed the problem with interfering with gesture navigation. 
Used an Android API for getting the gesture insets and shifted the scroll starting point from the edge of the screen

---

> _For features/enhancements:_
 - [ ] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [ ] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

2024-01-07 18:07 UTC, d4vidi requested changes
Nicely done 👍🏻
Some comments / suggestions / questions - inline 🙏🏻

2024-01-08 11:04 UTC, gosha212 commented on detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java
> +        return new int[]{offsetX, offsetY};
The function name was changed. View the full file. The function will calculate the offset and not the point. In my opinion it is abuse to use point for returning just the offset

2024-01-08 11:05 UTC, gosha212 commented on detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/ScrollHelperTest.kt
> +    private val viewMock = mockViewWithGestureNavigation(displayWidth, displayHeight)
Why? Every test starts a new instance of the test class and initiates the members

2024-01-08 11:10 UTC, gosha212 commented on detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/ScrollHelperTest.kt
> +class ScrollHelperTest {
We already have this tests in JS. Isn't it redundancy? I've made those tests mostly for debugging.

2024-01-08 11:17 UTC, gosha212 commented on detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/ScrollHelperTest.kt
> +        val amountInPx = getViewSafeScrollableRangePix(viewMock, MOTION_DIR_DOWN).toFloat()
What do you mean. I should calculate it manually without using the functions?

2024-01-08 11:18 UTC, gosha212 commented on detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java
> +            minY = gestureInsets.top;
The result can be >=0.
I'm not user what is the action item here?

2024-01-08 14:02 UTC, d4vidi commented on detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java
> +        return new int[]{offsetX, offsetY};
Yes,. Technically, this here is relying on production code in test code in order to test production code - not the best idea. For example, what if `getViewSafeScrollableRangePix` breaks and returns nothing but 0's. The test will not break... Everything should be deterministic, including the value of `amountInPx`.

2024-01-08 14:03 UTC, d4vidi commented on detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/ScrollHelperTest.kt
> +    private val viewMock = mockViewWithGestureNavigation(displayWidth, displayHeight)
You sure about that?

2024-01-08 14:06 UTC, d4vidi commented on detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/ScrollHelperTest.kt
> +        val amountInPx = getViewSafeScrollableRangePix(viewMock, MOTION_DIR_DOWN).toFloat()
Yes,. Technically, this here is relying on production code in test code in order to test production code - not the best idea. For example, what if `getViewSafeScrollableRangePix` breaks and returns nothing but 0's. The test will not break... Everything should be deterministic, including the value of `amountInPx`.

2024-01-08 16:03 UTC, d4vidi commented on detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/ScrollHelperTest.kt
> +    private val viewMock = mockViewWithGestureNavigation(displayWidth, displayHeight)
Yeah cool I checked and you're right! TIL

2024-01-08 16:04 UTC, d4vidi commented on detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/ScrollHelperTest.kt
> +        // Verify that the scroll started at the center of the view
?

2024-01-08 16:06 UTC, d4vidi commented on detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/ScrollHelperTest.kt
> +class ScrollHelperTest {
Yes but it keeps you're code quality high and will give you feedback on changes in a _very_ short feedback loop in the future

2024-01-09 16:21 UTC, d4vidi approved these changes
🔥

2024-01-10 07:08 UTC, merged