Upgrade/rn72 final
wix/Detox pull request #4336
Opened 2024-01-15 17:04 UTC by gosha212

## Description

- This pull request addresses the issue described here: #<?>

In this pull request, I have added support to RN 72 with backward compatibility to RN 71

---

> _For features/enhancements:_
 - [ ] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [ ] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

2024-01-17 16:02 UTC, d4vidi requested changes
Hey looks really good, but requires some subtle fixed. Please review 🙏🏻

2024-01-21 09:53 UTC, gosha212 commented on detox/android/build.gradle
> -        }
What do you mean? We don't need this because we are not using ndk in our project

2024-01-21 11:06 UTC, d4vidi commented on detox/test/e2e/33.attributes.test.js
> +  custom.describe.skipFromRNVersion(71)('of a legacy slider', () => {
This is not exported from the custom `describe`, but the `it`

2024-01-21 12:31 UTC, d4vidi approved these changes

2024-01-21 17:14 UTC, merged

2024-01-21 17:23 UTC, d4vidi commented
<img src="https://media1.giphy.com/media/3ohzdIuqJoo8QdKlnW/giphy-downsized.gif?cid=6104955epv3j3rdm1iv2twaibsvez841mfaj2ycmomeh2ace&ep=v1_gifs_translate&rid=giphy-downsized.gif&ct=g"/>