Feat/4175 new arch
wix/Detox pull request #4675
Opened 2024-12-24 16:21 UTC by gosha212

## Description

- This pull request addresses the issue described here: #4175

In this pull request, I have added support for the new arch in detox

---

> _For features/enhancements:_
 - [ ] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [ ] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

2025-01-13 07:18 UTC, asafkorem commented on .buildkite/jobs/pipeline.android_demo_app_rn_76.yml
> +  - label: ":android::react: (New Arch) - RN .76 + Android: Demo app"
Why not testing both new arch and old arch on .76?
Is that a breaking change?

2025-01-13 07:38 UTC, asafkorem commented
@gosha212 don't you crash on the `LanguageScreen`?

2025-01-13 15:33 UTC, asafkorem commented
we should check if our bridge native modules work with backward comp. or if there's something magically /hybrid that happens here

2025-01-13 16:08 UTC, d4vidi commented on .buildkite/jobs/pipeline.android_demo_app_rn_76.yml
> +  - label: ":android::react: (New Arch) - RN .76 + Android: Demo app"
I think it's ok for the demo app but the question is valid for the main test app; By now we know the backwards compatibility is feasible with a reasonable effort so let's take it

2025-01-14 05:49 UTC, asafkorem requested changes
In iOS we can check the env flag `process.env.RCT_NEW_ARCH_ENABLED`
We can use this when running new arch on android as well (for the tests)

2025-01-14 05:49 UTC, asafkorem commented on detox/test/e2e/33.attributes.test.js
> +    it.skip(':android: should have a boolean .value', async () => {
we should not skip this test for the legacy if it works there
let's add the skip marker for `@new-arch` and `@legacy` on `rnSkipper`.

2025-01-14 09:23 UTC, gosha212 commented on detox/test/e2e/33.attributes.test.js
> +    it.skip(':android: should have a boolean .value', async () => {
I think it will be easier to contribute to checkbox project =)

2025-01-14 13:27 UTC, d4vidi requested changes
Overall, great job. Lot's of notes on my end but we are nevertheless very close to finish 👑

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt
> +            host?.addReactInstanceEventListener(object : ReactInstanceEventListener {
`host?` is an issue... If we reach this subscribe() flow and host is null, we'd stay stuck forever

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt
>                  // That's why we have to check the reactContext regularly.
Can we Detox this comment a bit? 😄 Is it really an _ugly_ unexplained timing issue or do we understand things better now and give a good technical explanation (for future generations' sake)

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/reloader/ReactNativeReloader.kt
> +        }
Here too, if `reactHost` is null then reload would just fail silently

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/reloader/ReactNativeReloader.kt
> +        }
Regardless, maybe this would be a (little) bit cleaner:
```suggestion
        instrumentation.runOnMainSync {
            rnApplication.reactHost?.reload("Detox")
        }
```
I mean, `rnApplication` is a class member, so no need to hold an additional local var no top of that

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/timers/FabricTimersIdlingResource.kt
> +        return "FabricTimers"
```suggestion
        return "timers"
```
We don't want "Fabric" in the sync-debug logs

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/timers/FabricTimersIdlingResource.kt
> +            getChoreographer().postFrameCallback(this@FabricTimersIdlingResource)
Future note (todo?): Add ourselves as a callback in the timers module, in-sync with the longest current wait in queue*. Brut-force checking every 16ms was not the best idea, in retrospect.

_\* still below the window threshold..._

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/timers/FabricTimersIdlingResource.kt
> +        val hasActiveTimers: Boolean = method.call(timersManager, BUSY_WINDOW_THRESHOLD) as? Boolean ?: false
Why not use Reflect for this as well?

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/timers/FabricTimersIdlingResource.kt
> +        return Reflect.on(reactInstance).field("mJavaTimerManager").get() as JavaTimerManager
Could we outsource all reflection ugliness elsewhere? I want to say a `TimersManagerReflected` kind of wrapper but my idea is as good as yours (as long as this is put away from the core logic which this class holds)

2025-01-14 13:27 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/reloader/ReactNativeReloader.kt
> +        }
Anyways, nice that it's a simple `reactHost.reload()` call now 😄

2025-01-15 16:20 UTC, d4vidi commented on detox/android/detox/build.gradle
> +    }
on 2nd thought, maybe `implementation` would be a better idea here

2025-01-15 16:29 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt
> +            host?.addReactInstanceEventListener(object : ReactInstanceEventListener {
I see but here the code implicitly suggests that adding the listener is just "nice-to-have", maybe `host!!` would make it more explicit

2025-01-15 16:30 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/factory/FabricDetoxIdlingResourceFactoryStrategy.kt
> +                    ?: throw IllegalStateException("ReactContext is null")
So maybe:
```suggestion
                reactApplication.getCurrentReactContextSafe()
```

2025-01-15 16:32 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/uimodule/fabric/FabricUIManagerIdlingResources.kt
> +    }
Can fix?

2025-01-15 16:32 UTC, d4vidi commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/timers/JavaTimersReflected.kt
> +object JavaTimersReflected {
Cool

2025-01-15 16:33 UTC, d4vidi commented on detox/scripts/updateGradle.js
> +      console.log('gradle.properties patched successfully.');
WDYT? 😄

2025-01-16 12:43 UTC, gosha212 commented on detox/android/detox/build.gradle
> +    }
![Google Chrome 2025-01-16 14 42 50](https://github.com/user-attachments/assets/8314b4e6-c845-4902-9f44-e663bce54870)

2025-01-16 13:59 UTC, merged

2025-02-05 02:17 UTC, mikehardy commented
Hey @gosha212 - just wanted to say thanks for the new arch fixes in detox - I know it's a pain getting the ReactContext because I also had to fight my way through it in react-native-firebase and notifee, with all the symbols being different across versions but you need it to work on all the versions too, what a pain.

I tried the 20.33.0-prerelease.0 release and it works for me (at least with one trivial build.gradle patch that's already tracked here in an issue). 20.32.0 definitely didn't get the react context in new arch mode, but I've got all the correct adb logcat messages now indicating it has it with these PRs in the prerelease 🔥

2025-02-05 13:38 UTC, gosha212 commented
@mikehardy thanks for the warm words. The iOS is 99% ready

2025-02-05 21:49 UTC, mikehardy commented
react-native-firebase e2e app (my use case here) does almost no app interaction so we are not a great indicator of full-feature functionality, but it's working for us on react-native iOS platform as well as react-native-macos already, for basic app launch / terminate / ready-signaling behavior, so I'm well-pleased. Merged the PR with it already and our e2e app is able to test (and sadly, uncover some) new architecture issues

2025-02-09 20:14 UTC, d4vidi commented
@mikehardy thanks again for the kind words! 🙏🏻
On iOS, we've been finalizing some edge cases related to Detox's handling of app crash scenarios.

>...able to test (and sadly, uncover some) new architecture issues

Music to our ears... 🎶  whenever tests uncovers issue, we feel better about our work 😊

2025-08-16 16:37 UTC, mikehardy commented on detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/timers/JavaTimersReflected.kt
> +        return Reflect.on(reactInstance).field("mJavaTimerManager").get() as JavaTimerManager
Hey @gosha212 👋 

Saw two things here:

1- they converted this file to kotlin (first released in react-native 0.80) and it changed from `mJavaTimerManager` to the non-Hungarian notation `javaTimerManager`:

https://github.com/facebook/react-native/blame/0e6b94f4ab62a5cfa9cb770615e255fca31221f9/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactInstance.kt#L101

Maybe 

```kotlin

        try {
          return Reflect.on(reactInstance).field("mJavaTimerManager").get() as JavaTimerManager
        } catch (nsfe: NoSuchMethodException) {
          return Reflect.on(reactInstance).field("javaTimerManager").get() as JavaTimerManager
        }
```

2025-08-16 17:27 UTC, gosha212 commented
@mikehardy hi, there is already a new pr to support rn 80